apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storetheindex
resources:
- service-account.yaml
- assigner
- instances
- indexstar
- dhstore
- dhstore-ago2
- dhfind
- dhfind-ago2
- caskadht
- snapshots
- lookout
- cassette
- heyfil
- fdb-manager
- fdb-cluster
- dhstore-stateless
images:
- name: storetheindex
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/storetheindex/storetheindex # {"$imagepolicy": "storetheindex:storetheindex:name"}
  newTag: 20230601233715-9d2f7ccbd13dd304c0a3843969b9ddb8210ae6f1 # {"$imagepolicy": "storetheindex:storetheindex:tag"}
